spring:
  h2:
    console:
      path: /h2-console
      enabled: true
  datasource:
    url: jdbc:h2:file:../db/ms-employees;AUTO_SERVER=TRUE
    driver-class-name: org.h2.Driver
    username: admin
    password: admin123
  jpa:
    hibernate:
      ddl-auto: update